FROM quay.io/continuouspipe/php7.1-apache:latest

MAINTAINER "Kieren Evans <kieren.evans+cp-dockerfiles@inviqa.com>"

RUN curl -sL https://deb.nodesource.com/setup_7.x > /tmp/install-node.sh \
 && bash /tmp/install-node.sh \
 && apt-get update -qq -y \
 && DEBIAN_FRONTEND=noninteractive apt-get -qq -y --no-install-recommends install \
    mysql-client \
    nodejs \
 \
 # Clean the image \
 && apt-get auto-remove -qq -y \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 \
 # Install Drupal's CLI tool \
 && curl https://drupalconsole.com/installer -L -o /usr/local/bin/drupal \
 && chmod a+x /usr/local/bin/drupal

USER build

# Install Drupal's Drush tool
RUN composer global require drush/drush:~8.1.10 \
 && composer global clear-cache

USER root

RUN ln -s /home/build/.composer/vendor/bin/drush /usr/local/bin/

COPY ./etc/ /etc
COPY ./usr/ /usr
