#!/bin/bash

export PHP_MEMORY_LIMIT_CLI=${PHP_MEMORY_LIMIT_CLI:-${PHP_MEMORY_LIMIT}}

START_APACHE="$(convert_to_boolean_string "${START_APACHE:-${START_MODE_WEB:-false}}")"
export START_APACHE

export WEB_INCLUDES=${WEB_INCLUDES:-000-default-*}

export WEB_SSL_PROTOCOLS=${WEB_SSL_PROTOCOLS:-All -SSLv2 -SSLv3}

export AUTH_HTTP_FILE=${AUTH_HTTP_FILE:-/etc/apache2/htpasswd}
export AUTH_HTTP_TYPE=${AUTH_HTTP_TYPE:-Basic}
