language: bash

sudo: required

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck
  - docker pull lukasmartinelli/hadolint
  - docker pull quay.io/continuouspipe/ubuntu16.04:latest

script:
  - bash ./test.sh

after_success:
  - |
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" quay.io && bash ./build.sh && EOL_BUILD=true ./build.sh
    fi
  - |
    if [ "$TRAVIS_BRANCH" == "force-eol" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" quay.io && EOL_BUILD=true ./build.sh
    fi
