variables:
  FROM_TAG:
    name: FROM_TAG
    expression: '"dev-" ~ slugify(code_reference.branch)'

pipelines:
  - name: Production
    condition: 'code_reference.branch in ["cp-main"]'
    tasks: &ALL_IMAGES
      - third_level_dependency_images
      - second_level_dependency_images
      - first_level_dependency_images
      - no_dependency_images_a_g
      - no_dependency_images_h_m
      - no_dependency_images_n_r
      - no_dependency_images_s_z
      - first_level_dependency_eol_images
      - no_dependency_eol_images
    variables:
      - name: FROM_TAG
        expression: '"latest"'
  - name: Production EOL
    condition: 'code_reference.branch in ["cp-force-eol"]'
    tasks:
      - first_level_dependency_eol_images
      - no_dependency_eol_images
    variables:
      - name: FROM_TAG
        expression: '"latest"'
  - name: Feature Branches
    condition: '"Ready for Review" in pull_request.labels and not(code_reference.branch in ["main"])'
    tasks:
      - third_level_dependency_images
      - second_level_dependency_images
      - first_level_dependency_images
      - no_dependency_images_a_g
      - no_dependency_images_h_m
      - no_dependency_images_n_r
      - no_dependency_images_s_z

tasks:
  ##################################################
  # Build ubuntu first as most things depend on it #
  ##################################################
  third_level_dependency_images:
    build:
      environment:
        FROM_TAG: ${FROM_TAG}
      services:
        ubuntu:
          image: quay.io/continuouspipe/ubuntu16.04
          tag: ${FROM_TAG}
          reuse: false

  ################################
  # Build intermediate images #1 #
  ################################
  second_level_dependency_images:
    build:
      environment:
        FROM_TAG: ${FROM_TAG}
      services:
        nginx:
          image: quay.io/continuouspipe/nginx
          tag: ${FROM_TAG}
          reuse: false
        php72_apache:
          image: quay.io/continuouspipe/php7.2-apache
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '7.2'
            FROM_TAG: ${FROM_TAG}
        php71_apache:
          image: quay.io/continuouspipe/php7.1-apache
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '7.1'
            FROM_TAG: ${FROM_TAG}
        php70_apache:
          image: quay.io/continuouspipe/php7-apache
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '7.0'
            FROM_TAG: ${FROM_TAG}
        php56_apache:
          image: quay.io/continuouspipe/php5.6-apache
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '5.6'
            FROM_TAG: ${FROM_TAG}
        php72_nginx:
          image: quay.io/continuouspipe/php7.2-nginx
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '7.2'
            FROM_TAG: ${FROM_TAG}
        php71_nginx:
          image: quay.io/continuouspipe/php7.1-nginx
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '7.1'
            FROM_TAG: ${FROM_TAG}
        php70_nginx:
          image: quay.io/continuouspipe/php7-nginx
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '7.0'
            FROM_TAG: ${FROM_TAG}
        php56_nginx:
          image: quay.io/continuouspipe/php5.6-nginx
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '5.6'
            FROM_TAG: ${FROM_TAG}
        solr_4_10:
          image: quay.io/continuouspipe/solr4
          tag: ${FROM_TAG}
          reuse: false
        solr_6_2:
          image: quay.io/continuouspipe/solr6
          tag: ${FROM_TAG}
          reuse: false
        varnish:
          image: quay.io/continuouspipe/varnish4
          tag: ${FROM_TAG}
          reuse: false

  ################################
  # Build intermediate images #2 #
  ################################
  first_level_dependency_images:
    build:
      services:
        symfony_php72_nginx:
          image: quay.io/continuouspipe/symfony-php7.2-nginx
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '7.2'
            WEB_SERVER: nginx
            FROM_TAG: ${FROM_TAG}
        symfony_php71_nginx:
          image: quay.io/continuouspipe/symfony-php7.1-nginx
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '7.1'
            WEB_SERVER: nginx
            FROM_TAG: ${FROM_TAG}
        symfony_php72_apache:
          image: quay.io/continuouspipe/symfony-php7.2-apache
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '7.2'
            WEB_SERVER: apache
            FROM_TAG: ${FROM_TAG}
        symfony_php71_apache:
          image: quay.io/continuouspipe/symfony-php7.1-apache
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '7.1'
            WEB_SERVER: apache
            FROM_TAG: ${FROM_TAG}
        symfony_php70_apache:
          image: quay.io/continuouspipe/symfony-php7-apache
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '7'
            WEB_SERVER: apache
            FROM_TAG: ${FROM_TAG}

  ##############################
  # No dependency images (A-G) #
  ##############################
  no_dependency_images_a_g:
    build:
      environment:
        FROM_TAG: ${FROM_TAG}
      services:
        couchdb16:
          image: quay.io/continuouspipe/couchdb1.6
          tag: ${FROM_TAG}
          reuse: false
          environment:
            FROM_TAG: '1.6'
        drupal_php71_apache:
          image: quay.io/continuouspipe/drupal-php7.1-apache
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '7.1'
            FROM_TAG: ${FROM_TAG}
        drupal_php70_apache:
          image: quay.io/continuouspipe/drupal-php7-apache
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '7'
            FROM_TAG: ${FROM_TAG}
        drupal8_apache_php7:
          image: quay.io/continuouspipe/drupal8-apache-php7
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '7'
            FROM_TAG: ${FROM_TAG}
        drupal_php56_apache:
          image: quay.io/continuouspipe/drupal-php5.6-apache
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '5.6'
            FROM_TAG: ${FROM_TAG}
        drupal8_solr_4_10:
          image: quay.io/continuouspipe/drupal8-solr4
          tag: ${FROM_TAG}
          reuse: false
        drupal8_solr_6_2:
          image: quay.io/continuouspipe/drupal8-solr6
          tag: ${FROM_TAG}
          reuse: false
        drupal8_varnish:
          image: quay.io/continuouspipe/drupal8-varnish4
          tag: ${FROM_TAG}
          reuse: false
        elasticsearch17:
          image: quay.io/continuouspipe/elasticsearch1.7
          tag: ${FROM_TAG}
          reuse: false
          environment:
            FROM_TAG: '1.7'
        elasticsearch24:
          image: quay.io/continuouspipe/elasticsearch2.4
          tag: ${FROM_TAG}
          reuse: false
          environment:
            FROM_TAG: '2.4'
        elasticsearch55:
          image: quay.io/continuouspipe/elasticsearch5.5
          tag: ${FROM_TAG}
          reuse: false
          environment:
            FROM_TAG: '5.5'
        elasticsearch56:
          image: quay.io/continuouspipe/elasticsearch5.6
          tag: ${FROM_TAG}
          reuse: false
          environment:
            FROM_TAG: '5.6.9'
        ezplatform_php70_apache:
          image: quay.io/continuouspipe/ez6-apache-php7
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '7'
            FROM_TAG: ${FROM_TAG}
        ezplatform_php71_apache:
          image: quay.io/continuouspipe/ez6-php7.1-apache
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '7.1'
            FROM_TAG: ${FROM_TAG}

  ##############################
  # No dependency images (H-M) #
  ##############################
  no_dependency_images_h_m:
    build:
      environment:
        FROM_TAG: ${FROM_TAG}
      services:
        hem:
          image: quay.io/continuouspipe/hem1
          tag: ${FROM_TAG}
          reuse: false
        magento1_php56_apache:
          image: quay.io/continuouspipe/magento1-apache-php5.6
          tag: ${FROM_TAG}
          reuse: false
          environment:
            FROM_IMAGE: php5.6-apache
            WEB_SERVER: apache
            FROM_TAG: ${FROM_TAG}
        magento1_php56_nginx:
          image: quay.io/continuouspipe/magento1-nginx-php5.6
          tag: ${FROM_TAG}
          reuse: false
          environment:
            FROM_IMAGE: php5.6-nginx
            WEB_SERVER: nginx
            FROM_TAG: ${FROM_TAG}
        magento2_php70_nginx:
          image: quay.io/continuouspipe/magento2-nginx-php7
          tag: ${FROM_TAG}
          reuse: false
          environment:
            FROM_IMAGE: php7-nginx
            WEB_SERVER: nginx
            FROM_TAG: ${FROM_TAG}
            REQUIRE_HEM: 'true'
        magento2_php70_nginx_ng:
          image: quay.io/continuouspipe/magento2-nginx-php7-ng
          tag: ${FROM_TAG}
          reuse: false
          environment:
            FROM_IMAGE: php7-nginx
            WEB_SERVER: nginx
            FROM_TAG: ${FROM_TAG}
        magento2_php71_nginx:
          image: quay.io/continuouspipe/magento2-nginx-php7.1
          tag: ${FROM_TAG}
          reuse: false
          environment:
            FROM_IMAGE: php7.1-nginx
            WEB_SERVER: nginx
            FROM_TAG: ${FROM_TAG}
            REQUIRE_HEM: 'true'
        magento2_php71_nginx_ng:
          image: quay.io/continuouspipe/magento2-nginx-php7.1-ng
          tag: ${FROM_TAG}
          reuse: false
          environment:
            FROM_IMAGE: php7.1-nginx
            WEB_SERVER: nginx
            FROM_TAG: ${FROM_TAG}
        magento2_php72_nginx_ng:
          image: quay.io/continuouspipe/magento2-nginx-php7.2-ng
          tag: ${FROM_TAG}
          reuse: false
          environment:
            FROM_IMAGE: php7.2-nginx
            WEB_SERVER: nginx
            FROM_TAG: ${FROM_TAG}
        magento2_varnish:
          image: quay.io/continuouspipe/magento2-varnish4
          tag: ${FROM_TAG}
          reuse: false
        mailcatcher:
          image: quay.io/continuouspipe/mailcatcher
          tag: ${FROM_TAG}
          reuse: false
        memcached:
          image: quay.io/continuouspipe/memcached1.4
          tag: ${FROM_TAG}
          reuse: false
        mongodb34:
          image: quay.io/continuouspipe/mongodb3.4
          tag: ${FROM_TAG}
          reuse: false
          environment:
            FROM_TAG: '3.4'
        mongodb36:
          image: quay.io/continuouspipe/mongodb3.6
          tag: ${FROM_TAG}
          reuse: false
          environment:
            FROM_TAG: '3.6'
        mysql80:
          image: quay.io/continuouspipe/mysql8.0
          tag: ${FROM_TAG}
          reuse: false
          environment:
            FROM_TAG: '8.0'
        mysql57:
          image: quay.io/continuouspipe/mysql5.7
          tag: ${FROM_TAG}
          reuse: false
          environment:
            FROM_TAG: '5.7'
        mysql56:
          image: quay.io/continuouspipe/mysql5.6
          tag: ${FROM_TAG}
          reuse: false
          environment:
            FROM_TAG: '5.6'
        mysql55:
          image: quay.io/continuouspipe/mysql5.5
          tag: ${FROM_TAG}
          reuse: false
          environment:
            FROM_TAG: '5.5'

  ##############################
  # No dependency images (N-R) #
  ##############################
  no_dependency_images_n_r:
    build:
      environment:
        FROM_TAG: ${FROM_TAG}
      services:
        nginx_ingress_controller:
          image: quay.io/continuouspipe/nginx-ingress-controller
          tag: ${FROM_TAG}
          reuse: false
        nginx_reverse_proxy:
          image: quay.io/continuouspipe/nginx-reverse-proxy
          tag: ${FROM_TAG}
          reuse: false
        nodejs6:
          image: quay.io/continuouspipe/nodejs6
          tag: ${FROM_TAG}
          reuse: false
          environment:
            NODE_VERSION: "6.x"
            FROM_TAG: ${FROM_TAG}
        nodejs6_small:
          image: quay.io/continuouspipe/nodejs6-small
          tag: ${FROM_TAG}
          reuse: false
          environment:
            NODE_VERSION: "6.x"
            INSTALL_COMMON_PACKAGES: "false"
            FROM_TAG: ${FROM_TAG}
        nodejs7:
          image: quay.io/continuouspipe/nodejs7
          tag: ${FROM_TAG}
          reuse: false
          environment:
            NODE_VERSION: "7.x"
            FROM_TAG: ${FROM_TAG}
        nodejs7_small:
          image: quay.io/continuouspipe/nodejs7-small
          tag: ${FROM_TAG}
          reuse: false
          environment:
            NODE_VERSION: "7.x"
            INSTALL_COMMON_PACKAGES: "false"
            FROM_TAG: ${FROM_TAG}
        nodejs8:
          image: quay.io/continuouspipe/nodejs8
          tag: ${FROM_TAG}
          reuse: false
          environment:
            NODE_VERSION: "8.x"
            FROM_TAG: ${FROM_TAG}
        nodejs8_small:
          image: quay.io/continuouspipe/nodejs8-small
          tag: ${FROM_TAG}
          reuse: false
          environment:
            NODE_VERSION: "8.x"
            INSTALL_COMMON_PACKAGES: "false"
            FROM_TAG: ${FROM_TAG}
        phantomjs2:
          image: quay.io/continuouspipe/phantomjs2
          tag: ${FROM_TAG}
          reuse: false
        piwik_php71_apache:
          image: quay.io/continuouspipe/piwik-php7.1-apache
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: 7.1
            FROM_TAG: ${FROM_TAG}
        postgres94:
          image: quay.io/continuouspipe/postgres9.4
          tag: ${FROM_TAG}
          reuse: false
          environment:
            FROM_TAG: '9.4'
        postgres96:
          image: quay.io/continuouspipe/postgres9.6
          tag: ${FROM_TAG}
          reuse: false
          environment:
            FROM_TAG: '9.6'
        rabbitmq36_management:
          image: quay.io/continuouspipe/rabbitmq36-management
          tag: ${FROM_TAG}
          reuse: false
          environment:
            FROM_TAG: '3.6-management'
        rabbitmq37_management:
          image: quay.io/continuouspipe/rabbitmq37-management
          tag: ${FROM_TAG}
          reuse: false
          environment:
            FROM_TAG: '3.7-management'
        redis:
          image: quay.io/continuouspipe/redis3
          tag: ${FROM_TAG}
          reuse: false

  ##############################
  # No dependency images (S-Z) #
  ##############################
  no_dependency_images_s_z:
    build:
      environment:
        FROM_TAG: ${FROM_TAG}
      services:
        scala_sbt:
          image: quay.io/continuouspipe/scala-base
          tag: ${FROM_TAG}
          reuse: false
        ssh_forward:
          image: quay.io/continuouspipe/ssh-forward
          tag: ${FROM_TAG}
          reuse: false
        spryker_php71_nginx:
          image: quay.io/continuouspipe/spryker-php7.1-nginx
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '7.1'
            WEB_SERVER: nginx
            FROM_TAG: ${FROM_TAG}
        spryker_php71_apache:
          image: quay.io/continuouspipe/spryker-php7.1-apache
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '7.1'
            WEB_SERVER: apache
            FROM_TAG: ${FROM_TAG}
        spryker_php72_nginx:
          image: quay.io/continuouspipe/spryker-php7.2-nginx
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '7.2'
            WEB_SERVER: nginx
            FROM_TAG: ${FROM_TAG}
        spryker_php72_apache:
          image: quay.io/continuouspipe/spryker-php7.2-apache
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '7.2'
            WEB_SERVER: apache
            FROM_TAG: ${FROM_TAG}
        spryker_php73_nginx:
          image: quay.io/continuouspipe/spryker-php7.3-nginx
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '7.3'
            WEB_SERVER: nginx
            FROM_TAG: ${FROM_TAG}
        spryker_php73_apache:
          image: quay.io/continuouspipe/spryker-php7.3-apache
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '7.3'
            WEB_SERVER: apache
            FROM_TAG: ${FROM_TAG}
        symfony_php70_nginx:
          image: quay.io/continuouspipe/symfony-php7-nginx
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '7'
            WEB_SERVER: nginx
            FROM_TAG: ${FROM_TAG}
        symfony_php56_nginx:
          image: quay.io/continuouspipe/symfony-php5.6-nginx
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '5.6'
            WEB_SERVER: nginx
            FROM_TAG: ${FROM_TAG}
        symfony_php56_apache:
          image: quay.io/continuouspipe/symfony-php5.6-apache
          tag: ${FROM_TAG}
          reuse: false
          environment:
            PHP_VERSION: '5.6'
            WEB_SERVER: apache
            FROM_TAG: ${FROM_TAG}
        symfony_pack:
          image: quay.io/continuouspipe/symfony-pack
          tag: ${FROM_TAG}
          reuse: false
          environment:
            FROM_TAG: ${FROM_TAG}
        tideways:
          image: quay.io/continuouspipe/tideways
          tag: ${FROM_TAG}
          reuse: false

  first_level_dependency_eol_images:
    build:
      services:
        php55_nginx:
          image: quay.io/continuouspipe/eol-php5.5-nginx
          tag: ${FROM_TAG}
          reuse: false
          build_directory: ./php/
          docker_file_path: ./Dockerfile-nginx-phpsource
          environment:
            PHP_FULL_VERSION: '5.5.38'
            FROM_TAG: ${FROM_TAG}

  no_dependency_eol_images:
    build:
      services:
        magento1_php55_nginx:
          image: quay.io/continuouspipe/eol-magento1-nginx-php5.5
          tag: ${FROM_TAG}
          reuse: false
          build_directory: ./magento1/
          environment:
            FROM_IMAGE: eol-php5.5-nginx
            WEB_SERVER: nginx
            FROM_TAG: ${FROM_TAG}
