#!/bin/bash

export WORK_DIRECTORY=${WORK_DIRECTORY:-/app}
export CODE_OWNER=${CODE_OWNER:-build}
export CODE_GROUP=${CODE_GROUP:-build}

START_CRON=${START_CRON:-false}
START_CRON="$(convert_to_boolean_string "$START_CRON")"
export START_CRON

set +e
IS_CHOWN_FORBIDDEN="$(is_chown_forbidden)"
export IS_CHOWN_FORBIDDEN

IS_VBOXSF_MOUNTPOINT="$(is_vboxsf_mountpoint)"
export IS_VBOXSF_MOUNTPOINT

IS_APP_MOUNTPOINT="$(is_app_mountpoint)"
export IS_APP_MOUNTPOINT
set -e

DEVELOPMENT_MODE="$(convert_to_boolean_string_zero_is_true "${DEVELOPMENT_MODE:-${IS_APP_MOUNTPOINT}}")"
export DEVELOPMENT_MODE

RUN_BUILD="$(convert_to_boolean_string "${RUN_BUILD:-true}")"
export RUN_BUILD

APP_USER_LOCAL="$(convert_to_boolean_string "${APP_USER_LOCAL:-${IS_VBOXSF_MOUNTPOINT}}")"
export APP_USER_LOCAL

APP_USER_LOCAL_RANDOM="$(convert_to_boolean_string "${APP_USER_LOCAL_RANDOM:-false}")"
export APP_USER_LOCAL_RANDOM

export BUILD_USER_SSH_PRIVATE_KEY=${BUILD_USER_SSH_PRIVATE_KEY:-}
export BUILD_USER_SSH_PUBLIC_KEY=${BUILD_USER_SSH_PUBLIC_KEY:-}
export BUILD_USER_SSH_KNOWN_HOSTS=${BUILD_USER_SSH_KNOWN_HOSTS:-}
