#!/bin/bash

export WORK_DIRECTORY=${WORK_DIRECTORY:-/app}
export CODE_OWNER=${CODE_OWNER:-build}
export CODE_GROUP=${CODE_GROUP:-build}

set +e
is_chown_forbidden
export IS_CHOWN_FORBIDDEN=$?

is_vboxsf_mountpoint
export IS_VBOXSF_MOUNTPOINT=$?
set -e

export DEVELOPMENT_MODE=${DEVELOPMENT_MODE:-${IS_CHOWN_FORBIDDEN}}
export APP_USER_LOCAL=${APP_USER_LOCAL:-${IS_VBOXSF_MOUNTPOINT}}
export APP_USER_LOCAL_RANDOM=${APP_USER_LOCAL_RANDOM:-false}
