#!/bin/bash

export MAGENTO_ADMIN_IP_WHITELIST=${MAGENTO_ADMIN_IP_WHITELIST:-$AUTH_IP_WHITELIST}

deprecate_env_var MAGENTO_RUN_BUILD RUN_BUILD

if [ "$IMAGE_VERSION" -ge 3 ]; then
  if [ "$MAGENTO_MODE" = 'production' ]; then
    export PRODUCTION_ENVIRONMENT="true"
  fi
else
  export BUILD_DEVELOPMENT_MODE=${BUILD_DEVELOPMENT_MODE:-false}
  export BUILD_PRODUCTION_ENVIRONMENT=${BUILD_PRODUCTION_ENVIRONMENT:-true}
  export BUILD_MAGENTO_MODE=${BUILD_MAGENTO_MODE:-production}

  PRODUCTION_ENVIRONMENT="$(convert_to_boolean_string "${PRODUCTION_ENVIRONMENT:-false}")"
  export PRODUCTION_ENVIRONMENT
fi

# Support older configurations by setting original env vars
export REDIS_HOST_PORT=${REDIS_PORT}

MAGENTO_ENTERPRISE_EDITION=$(convert_to_boolean_string "${MAGENTO_ENTERPRISE_EDITION:-$(run_return_boolean has_composer_package "magento/product-enterprise-edition")}")
export MAGENTO_ENTERPRISE_EDITION

export MAGENTO_VERSION="${MAGENTO_VERSION:-$(detect_magento_version)}"

if [ -z "${ASSETS_PATH:-}" ] || [ -z "${ASSETS_S3_BUCKET_PATH:-}" ]; then
  FORCE_DATABASE_DROP="$(convert_to_boolean_string "${FORCE_DATABASE_DROP:-false}")"
  export FORCE_DATABASE_DROP

  export AWS_S3_BUCKET=${AWS_S3_BUCKET:-}
  export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
  export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
  export ASSET_DOWNLOAD_EXCLUDE_PATTERN=${ASSET_DOWNLOAD_EXCLUDE_PATTERN:-}
  export ASSET_ARCHIVE_PATH=${ASSET_ARCHIVE_PATH:-tools/assets/development/media.files.tgz}
  export DATABASE_ARCHIVE_PATH=${DATABASE_ARCHIVE_PATH:-tools/assets/development/magentodb.sql.gz}
  export ASSET_DOWNLOAD_ENVIRONMENTS=${ASSET_DOWNLOAD_ENVIRONMENTS:-development}
fi
