#!/bin/bash

# Relative WEB_DIRECTORY converted to absolute path
if ! [[ "$WEB_DIRECTORY" =~ ^/ ]]; then
  export WEB_DIRECTORY=${WORK_DIRECTORY}/${WEB_DIRECTORY}
fi

if [ "${WEB_HTTP}" == "true" ]; then
  export WEB_HTTPS_ONLY=false
else
  export WEB_HTTPS_ONLY=${WEB_HTTPS_ONLY:-$WEB_HTTPS}
fi

DEFAULT_COMPOSER_FLAGS="--no-interaction --optimize-autoloader"

if [ -z "$DEVELOPMENT_MODE" ] || [ "$DEVELOPMENT_MODE" != 'true' ]; then
  DEFAULT_COMPOSER_FLAGS="${DEFAULT_COMPOSER_FLAGS} --no-dev"
fi
export COMPOSER_INSTALL_FLAGS=${COMPOSER_INSTALL_FLAGS:-$DEFAULT_COMPOSER_FLAGS}
