FROM quay.io/continuouspipe/php7.1-apache:latest

MAINTAINER Alex Biddle <alex.biddle+cp-dockerfiles@inviqa.com>

WORKDIR /app/web/piwik
RUN curl -L -O https://builds.piwik.org/latest.tar.gz && \
    tar --strip 1 -xzf latest.tar.gz && \
    rm latest.tar.gz

RUN chown -R build:www-data ./*
RUN chmod -R 0755 ./*
RUN chmod -R 0775 tmp \
    config