#!/bin/bash

# Relative WEB_DIRECTORY converted to absolute path
if ! [[ "$WEB_DIRECTORY" =~ ^/ ]]; then
  export WEB_DIRECTORY=${WORK_DIRECTORY}/${WEB_DIRECTORY}
fi

if [ "${WEB_HTTP}" == "true" ]; then
  export WEB_HTTPS_ONLY=false
else
  export WEB_HTTPS_ONLY=${WEB_HTTPS_ONLY:-$WEB_HTTPS}
fi

if [ -z "${APP_ENDPOINT_REGEX:-}" ]; then
  if [ "${APP_ENDPOINT_STRICT}" == "true" ]; then
    APP_ENDPOINT_REGEX=$(php -r 'echo preg_quote(getenv("APP_ENDPOINT"));')
  else
    APP_ENDPOINT_REGEX=".*\\.php"
  fi
  export APP_ENDPOINT_REGEX
fi

DEFAULT_COMPOSER_FLAGS="--no-interaction --optimize-autoloader"

if [ -z "$DEVELOPMENT_MODE" ] || [ "$DEVELOPMENT_MODE" != 'true' ]; then
  DEFAULT_COMPOSER_FLAGS="${DEFAULT_COMPOSER_FLAGS} --no-dev"
fi
export COMPOSER_INSTALL_FLAGS=${COMPOSER_INSTALL_FLAGS:-$DEFAULT_COMPOSER_FLAGS}

if [ "$DEVELOPMENT_MODE" != "true" ] && [ "$PHP_OPCACHE_VALIDATE_TIMESTAMPS_IS_DEFAULT" == "true" ]; then
  export PHP_OPCACHE_VALIDATE_TIMESTAMPS=${PHP_OPCACHE_VALIDATE_TIMESTAMPS:-0}
fi
