FROM quay.io/continuouspipe/php{{PHP_VERSION}}-{{WEB_SERVER}}:latest

MAINTAINER Hardik Gajjar <hardik.gajjar@inviqa.com>

RUN curl -sL https://deb.nodesource.com/setup_6.x > /tmp/install-node.sh \
 && bash /tmp/install-node.sh \
 && apt-get update -qq -y \
 && DEBIAN_FRONTEND=noninteractive apt-get -qq -y --no-install-recommends install \
    build-essential \
    graphviz \
    nodejs \
    php{{PHP_VERSION}}-gmp \
    redis-tools \
 \
 # Clean the image \
 && apt-get auto-remove -qq -y \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

COPY ./{{WEB_SERVER}}/ /
COPY ./etc/ /etc/
COPY ./usr/ /usr/
